### ISSUE TITLE
New URL?

### ISSUE THREAD

**Issue by AntoineSoetewey** [jaytimm/jtimm-web#1]
Dear @jaytimm,

It seems that your old url https://www.jtimm.net/2020/05/26/corp-comp-ling-covid19/ is broken. Do you have a new one to replace it?

Thanks in advance!

**Comment by jaytimm** [comment]
Hi -- I have re-worked my website, and lost some links in the process.

I have attached an html of the previous post.

**Comment by AntoineSoetewey** [comment]
Unless I’m mistaken, I don’t see any file attached.

**Comment by jaytimm** [comment]
I emailed it to you.  Hopefully you received it.

**Comment by AntoineSoetewey** [comment]
Received, thanks!
